-- =============================================================================
-- Criar o banco do de-match do zero (rode DEPOIS do wipe_de_match.sql)
-- =============================================================================
-- Arquivo só com comandos de criação (CREATE / ALTER para ligar RLS).
-- Não use “IF NOT EXISTS” nem DROP aqui: o banco deve estar limpo.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Perfil: nome e tipo de acesso (login/senha ficam no Auth do Supabase)
-- ---------------------------------------------------------------------------
CREATE TABLE public.perfil (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  nome_completo text NOT NULL DEFAULT '',
  perfil_acesso text NOT NULL DEFAULT 'voluntario'
    CHECK (perfil_acesso IN ('administrador', 'voluntario', 'validador')),
  data_atualizacao timestamptz DEFAULT NOW()
);

COMMENT ON TABLE public.perfil IS 'Dados do usuário logado: nome exibido e papel no sistema.';

ALTER TABLE public.perfil ENABLE ROW LEVEL SECURITY;

CREATE POLICY perfil_ler_proprio
  ON public.perfil FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY perfil_inserir_proprio
  ON public.perfil FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY perfil_atualizar_proprio
  ON public.perfil FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Quando nasce um usuário no Auth, cria a linha correspondente aqui
CREATE FUNCTION public.fn_novo_usuario_cria_perfil()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  meta_perfil text;
  perfil_escolhido text;
BEGIN
  meta_perfil := lower(trim(COALESCE(new.raw_user_meta_data->>'perfil_acesso', '')));
  perfil_escolhido := CASE
    WHEN meta_perfil IN ('voluntario', 'validador') THEN meta_perfil
    ELSE 'voluntario'
  END;

  INSERT INTO public.perfil (id, nome_completo, perfil_acesso)
  VALUES (
    new.id,
    COALESCE(NULLIF(trim(new.raw_user_meta_data->>'nome_completo'), ''), ''),
    perfil_escolhido
  );

  RETURN new;
END;
$$;

CREATE TRIGGER ao_cadastrar_usuario
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.fn_novo_usuario_cria_perfil();

-- Só administrador pode mudar o campo perfil_acesso (ninguém vira admin sozinho pelo app)
CREATE FUNCTION public.fn_so_admin_muda_perfil()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Com usuário logado no app: só administrador altera perfil_acesso.
  -- No SQL Editor do Supabase, auth.uid() costuma ser NULL (sem JWT): aí não bloqueia,
  -- para você poder promover o primeiro admin com um UPDATE manual.
  IF tg_op = 'UPDATE' AND new.perfil_acesso IS DISTINCT FROM old.perfil_acesso THEN
    IF auth.uid() IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso = 'administrador'
    ) THEN
      RAISE EXCEPTION 'Apenas administrador pode alterar o perfil de acesso';
    END IF;
  END IF;
  RETURN new;
END;
$$;

CREATE TRIGGER antes_de_atualizar_perfil
  BEFORE UPDATE ON public.perfil
  FOR EACH ROW EXECUTE PROCEDURE public.fn_so_admin_muda_perfil();

-- Quem já existia no Auth mas não tinha linha em perfil (útil após montar o banco)
INSERT INTO public.perfil (id, nome_completo, perfil_acesso)
SELECT u.id, '', 'voluntario'
FROM auth.users u
WHERE NOT EXISTS (SELECT 1 FROM public.perfil p WHERE p.id = u.id);

-- ---------------------------------------------------------------------------
-- Animais, adoções, eventos
-- ---------------------------------------------------------------------------
CREATE TABLE public.animal (
  id_animal bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_animal text NOT NULL,
  raca text,
  foto text,
  descricao_historia text,
  castrado boolean NOT NULL DEFAULT false,
  vacinacao text,
  localizacao text,
  disponibilidade text NOT NULL,
  observacoes text,
  sexo text,
  porte text,
  data_nascimento date,
  data_cadastro timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.adocao (
  id_operacao bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_operacao timestamptz NOT NULL DEFAULT NOW(),
  termo_adocao text NOT NULL,
  id_usuario uuid NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
  id_animal bigint NOT NULL REFERENCES public.animal (id_animal) ON DELETE RESTRICT,
  UNIQUE (id_animal)
);

CREATE INDEX idx_adocao_usuario ON public.adocao (id_usuario);

CREATE TABLE public.evento (
  id_evento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_evento text NOT NULL,
  data_evento timestamptz NOT NULL DEFAULT NOW(),
  id_usuario uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  id_animal bigint NOT NULL REFERENCES public.animal (id_animal) ON DELETE CASCADE
);

CREATE INDEX idx_evento_usuario ON public.evento (id_usuario);
CREATE INDEX idx_evento_animal ON public.evento (id_animal);

ALTER TABLE public.animal ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adocao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evento ENABLE ROW LEVEL SECURITY;

CREATE POLICY animal_ver_autenticado
  ON public.animal FOR SELECT TO authenticated USING (true);

-- Voluntário: cadastrar e editar (caso de uso). Validador e administrador também.
CREATE POLICY animal_inserir_equipe
  ON public.animal FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador', 'voluntario')
    )
  );

CREATE POLICY animal_atualizar_equipe
  ON public.animal FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador', 'voluntario')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador', 'voluntario')
    )
  );

CREATE POLICY animal_apagar_somente_admin
  ON public.animal FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso = 'administrador'
    )
  );

CREATE POLICY adocao_ver_proprio_ou_equipe
  ON public.adocao FOR SELECT TO authenticated
  USING (
    id_usuario = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador')
    )
  );

CREATE POLICY adocao_inserir_proprio
  ON public.adocao FOR INSERT TO authenticated
  WITH CHECK (id_usuario = auth.uid());

CREATE POLICY adocao_atualizar_equipe
  ON public.adocao FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador')
    )
  );

CREATE POLICY evento_ver_proprio_ou_equipe
  ON public.evento FOR SELECT TO authenticated
  USING (
    id_usuario = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador')
    )
  );

CREATE POLICY evento_inserir_proprio
  ON public.evento FOR INSERT TO authenticated
  WITH CHECK (id_usuario = auth.uid());

CREATE POLICY evento_atualizar_equipe
  ON public.evento FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador')
    )
  );

CREATE POLICY evento_apagar_equipe
  ON public.evento FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.perfil p
      WHERE p.id = auth.uid() AND p.perfil_acesso IN ('administrador', 'validador')
    )
  );
